# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-23 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(max_length=50)),
                ('note_date', models.DateTimeField(verbose_name='date created')),
                ('note_body', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absorbance', models.DecimalField(decimal_places=3, max_digits=4)),
                ('concentration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('standard', models.BooleanField()),
                ('note_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_notebook.LabNote')),
            ],
        ),
    ]
